micronaut:
  application:
    name: keymanagerGrpc
grpc:
  server:
    port: '50051'
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/pix
#    dialect: POSTGRES
#    driverClassName: org.postgresql.Driver
#    schema-generate: CREATE_DROP
#    username: 'postgres'
#    password: 'P@ssw0rd'

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bc:
  pix:
    url: 'http://localhost:8082'